# 2029165

## Task 1 - Train data

![lesson learnt - didn't save responses - uiii](./trains/2029165_didn't%20save%20the%20response.png "task-1")


## Task 2 - Number Manamgement

- The response sometimes returns the error "error occured". It is because the response is taking more than 500ms (due to several reasons like huge data or high traffic in the API call).
- As clearly mentioned in the question, the given timeout is strictly respeced in the code.
- the response received from the tastcase is same as given in the document.

![task 2 resposnse](./number_management/2029165.png "Task-2")